language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - TESTDATA_DIR=$HOME/testdata

addons:
  apt:
    packages:
    - libspatialite-dev
    - swig2.0

python:
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gdal-bin python-gdal python3-gdal libproj-dev libgdal-dev git -y

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install git+https://github.com/johntruckenbrodt/pyroSAR.git@dev
  - python setup.py install

script:
  - coverage run --source ci_testing/ -m pytest -s

after_success:
- coveralls
