language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - TESTDATA_DIR=$HOME/testdata
   
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - libudunits2-dev
      - python-gdal
      - python3-gdal
      - libspatialite-dev
      - swig2.0
      - libproj-dev
      - gdal-bin

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - wget -O esa-snap_sentinel_unix_6_0.sh http://step.esa.int/downloads/6.0/installers/esa-snap_sentinel_unix_6_0.sh
  - sudo chmod +x esa-snap_sentinel_unix_6_0.sh
  - yes "" | ./esa-snap_sentinel_unix_6_0.sh
  - export PATH=$PATH:/opt/snap/bin/

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - pip install git+https://github.com/johntruckenbrodt/pyroSAR.git@dev
  - python setup.py install

script:
  - coverage run --source ci_testing/ -m pytest -s

after_success:
- coveralls
